# This is a basic workflow to help you get started with Actions

name: Version

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Get next version
        uses: reecetech/version-increment@2024.4.4
        id: version
        with:
          scheme: semver
          prerelease: false
          draft: false
          release_branch: main

      - name: Create version number file in release and update
        run: |
          echo ${{ steps.version.outputs.version }} > version

      - name: Zip Release
        run: |
          zip -r release.zip .

      - name: Upload Release
        uses: softprops/action-gh-release@v2.0.5
        with:
          files: release.zip
          tag_name: ${{ steps.version.outputs.version }}
