# This is a basic workflow to help you get started with Actions

name: Version

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Get pull request title and check for mayor, minor or patch
        id: tag_name
        run: |
          if [[ ${{ github.event.pull_request.title }} == *"mayor"* ]]; then
            echo "versionType=mayor" >> "$GITHUB_OUTPUT"
          elif [[ ${{ github.event.pull_request.title }} == *"minor"* ]]; then
            echo "versionType=minor" >> "$GITHUB_OUTPUT"
          elif [[ ${{ github.event.pull_request.title }} == *"patch"* ]]; then
            echo "versionType=patch" >> "$GITHUB_OUTPUT"
          else
            echo "versionType=patch" >> "$GITHUB_OUTPUT"
          fi

      - name: Get next version
        uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          scheme: semver
          increment: ${{ steps.tag_name.outputs.versionType }}
